### ISSUE TITLE
While creating a new assistant got a JS error from the webchat injector 

### ISSUE THREAD

**Issue by meelie** [Yeldaai/chat-plugin#26] opened 2019-05-13 13:53 UTC
**Describe the bug**
While creating a new assistant got a JS error from the webchat injector CF  screenshot (from creation to step 1, after selecting voice)

**Screenshots**
![image](https://user-images.githubusercontent.com/5340081/57623276-be994680-758f-11e9-8f3a-25d613b57441.png)

**Environment**
Staging BO, creating a new assistant

**Comment by d-weber** [comment] 2019-05-13 14:27
I can't reproduce

**Comment by d-weber** [comment] 2019-05-13 14:28
Tell me if it's still occur after a hard-refresh :)

**Comment by d-weber** [comment] 2019-05-13 14:35
Ok did reproduce finally, fixing it on frontend, closing this one

**Closed by d-weber** 2019-05-13 14:35 UTC
Labels: bug
